name: Run test suite
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - '25.1'
          - '26.1'
          - '27.1'

    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: conao3/setup-cask@master

    - name: Download ripgrep
      run: curl -LO https://github.com/BurntSushi/ripgrep/releases/download/12.1.1/ripgrep_12.1.1_amd64.deb
    - name: Install ripgrep
      run: sudo dpkg -i ripgrep_12.1.1_amd64.deb

    - uses: actions/checkout@v2
    - name: Test
      env:
        COVERALLS_FLAG_NAME: Emacs ${{ matrix.emacs_version }}
        COVERALLS_PARALLEL: 1
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cask install
        cask exec ert-runner

    - if: matrix.matrix.emacs_version == '27.1'
      uses: actions/upload-artifact@v2
      with:
        name: undercover-report
        path: /tmp/undercover-report.json

  finalize:
    runs-on: ubuntu-latest
    if: always()
    needs: test
    steps:
    - uses: codecov/codecov-action@v1
      with:
        files: /tmp/undercover-report.json
